name: Deploy Spring Boot app to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
  ECS_CLUSTER_NAME: ${{secrets.ECS_CLUSTER_NAME}}
  ECS_SERVICE_NAME: ${{secrets.ECS_SERVICE_NAME}}
  ECS_TASK_DEFINITION: ${{secrets.ECS_TASK_DEFINITION}}
  CONTAINER_NAME: ${{secrets.CONTAINER_NAME}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  IMAGE_TAG: 381492153714.dkr.ecr.$AWS_REGION.amazonaws.com/${{secrets.ECR_REPOSITORY}}:latest
  TASK_DEFINITION_FILE: .aws/task-definition.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 381492153714.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{env.IMAGE_TAG}} --build-arg JAR_FILE=target/*.jar .

      - name: Push image to Amazon ECR
        run: docker push ${{env.IMAGE_TAG}}

      - name: Fill in image URI for ECS task definition
        run: sed -i "s|replace-this-later|${{env.IMAGE_TAG}}|" ${{env.TASK_DEFINITION_FILE}}

      - name: Register task definition
        id: task-def
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://${{env.TASK_DEFINITION_FILE}} --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update service
        run: aws ecs update-service --cluster ${{env.ECS_CLUSTER_NAME}} --service ${{env.ECS_SERVICE_NAME}} --task-definition ${{ env.TASK_DEF_ARN }}